### ISSUE TITLE
HW12 choices

### ISSUE THREAD

**Issue by kjacks21** [kjacks21/swe619-fall2018#12]
https://cs.gmu.edu/~pammann/619/assigns/assign12-13.html

What'll it be? I like either 3, 5, or 6. Prefer to do the easiest one this week given the holiday weekend and how little I'll be able to get done.

EDIT: 3 is just copy pasta, so that's my vote for this week.

**Comment by 1000DS000000** [comment]
I agree with either 5 or 6 for next week as well.
